"""Package metadata"""
TITLE = "aiosfstream"
DESCRIPTION = "Salesforce Streaming API client for asyncio"
KEYWORDS = "salesforce asyncio aiohttp comet cometd bayeux push streaming"
URL = "https://github.com/robertmrk/aiosfstream"
VERSION = "0.2.1"
AUTHOR = "Róbert Márki"
AUTHOR_EMAIL = "gsmiko@gmail.com"
